service: mtgml-storage

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

  userBucket: ${self:service}-${self:custom.stage}-user-bucket

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

resources:
  # S3
  - ${file(resources/s3.yml)}
