service: mtgml-database

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  usersTable: ${self:custom.stage}-users
  subscriptionsTable: ${self:custom.stage}-subscriptions
  userDecksTable: ${self:custom.stage}-user-decks
  userCardsTable: ${self:custom.stage}-user-cards

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      convertEmptyValues: true
      migrate: true

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

resources:
  # DynamoDB Tables
  - ${file(resources/dynamodb-tables.yml)}
