Resources:
  # All users (free and paying)
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.usersTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  # All subscriptions (subscription accounts)
  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.subscriptionsTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  # Public decks (MPL, etc...)
  GlobalDecksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.globalDecksTable}
      AttributeDefinitions:
        - AttributeName: deckId
          AttributeType: S
      KeySchema:
        - AttributeName: deckId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  # All cards (from Scryfall)
  GlobalCardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.globalCardsTable}
      AttributeDefinitions:
        - AttributeName: cardId
          AttributeType: S
      KeySchema:
        - AttributeName: cardId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  # User decks
  UserDecksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userDecksTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deckId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deckId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  # User cards
  UserCardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userCardsTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deckId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deckId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
