Resources:
  # All users (free and paying)
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.usersTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  # All subscriptions (subscription accounts)
  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.subscriptionsTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  # Public decks (MPL, etc...)
  GlobalDecksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.globalDecksTable}
      AttributeDefinitions:
        - AttributeName: deckId
          AttributeType: S
      KeySchema:
        - AttributeName: deckId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  # All cards (from Scryfall)
  GlobalCardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.globalCardsTable}
      AttributeDefinitions:
        - AttributeName: cardId
          AttributeType: S
      KeySchema:
        - AttributeName: cardId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  # User decks
  UserDecksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userDecksTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deckId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deckId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  # User cards
  UserCardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userCardsTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deckId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deckId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

Outputs:
  UsersTableArn:
    Value:
       Fn::GetAtt:
        - UsersTable
        - Arn
    Export:
      Name: ${self:custom.stage}-UsersTableArn
  SubscriptionsTableArn:
    Value:
       Fn::GetAtt:
        - SubscriptionsTable
        - Arn
    Export:
      Name: ${self:custom.stage}-SubscriptionsTableArn
  GlobalDecksTableArn:
    Value:
       Fn::GetAtt:
        - GlobalDecksTable
        - Arn
    Export:
      Name: ${self:custom.stage}-GlobalDecksTableArn
  GlobalCardsTableArn:
    Value:
       Fn::GetAtt:
        - GlobalCardsTable
        - Arn
    Export:
      Name: ${self:custom.stage}-GlobalCardsTableArn
  UserDecksTableArn:
    Value:
       Fn::GetAtt:
        - UserDecksTable
        - Arn
    Export:
      Name: ${self:custom.stage}-UserDecksTableArn
  UserCardsTableArn:
    Value:
       Fn::GetAtt:
        - UserCardsTable
        - Arn
    Export:
      Name: ${self:custom.stage}-UserCardsTableArn
